# Generated by Django 5.1.2 on 2024-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key='cid', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('loanamount', models.IntegerField()),
                ('dob', models.DateField()),
                ('contactnumber', models.IntegerField()),
            ],
        ),
    ]
